### ISSUE TITLE
Unable to login using default password

### ISSUE THREAD

**Issue by jgera** [johndavedecano/PHPLaravelGymManagementSystem#3]
i am unable to login using default details
admin@admin.com
password

**Comment by adityaditchu** [comment]
How to run the Telugu-OCR ??i'm getting some errors...which one is the final one???

**Comment by johndavedecano** [comment]
Check the seeder file

**Comment by YaruTsai** [comment]
I have the same question.
I check the seeder file. It has the DatabaseSeeder.php in /var/www/html/gym/app/database/seeds.
But I couldn't login in login page using default account.
May you help me how to solve it???

**Comment by johndavedecano** [comment]
Hi guys i will update these later today thanks sorry for the inconvenience

**Comment by YaruTsai** [comment]
Excuse me. Did you update the code?
