### ISSUE TITLE
php errors

### ISSUE THREAD

**Issue by mohsenuss91** [johndavedecano/PHPLaravelGymManagementSystem#4]
Warning: require(\GymManagementSystemPHPLaravel\bootstrap/../vendor/autoload.php) [function.require]: failed to open stream: No such file or directory in \GymManagementSystemPHPLaravel\bootstrap\autoload.php on line 17

Fatal error: require() [function.require]: Failed opening required \GymManagementSystemPHPLaravel\bootstrap/../vendor/autoload.php' (include_path='.;C:\php5\pear') in \GymManagementSystemPHPLaravel\bootstrap\autoload.php on line 17

**Comment by johndavedecano** [comment]
composer install
